use_frameworks!

platform :ios, '9.0'

target 'AniScrollviewDemo_Example' do
  pod 'AniScrollviewDemo', :path => '../'

  target 'AniScrollviewDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
